#! /bin/bash

DEBUG=0

# Check for required /etc/snapshots.list
[ -e /etc/snapshots.list ] || echo "ERROR: /etc/snapshots.list is required"
[ -e /etc/snapshots.list ] || exit 1

# Read btrfs volumes to snapshot from /etc/snapshots.list
VOLUMES=$(cat /etc/snapshots.list)

for v in $VOLUMES; do
    # Check last char, must be a '/'
    if [ x"${v: -1}" != x'/' ]; then
        echo "ERROR: check /etc/snapshots.list, $v should end with a '/'"
        exit 1
    fi
    # Check if snapshot is already done
    btrfs subvolume show $v.daily-$(date +%Y-%m-%d) > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo -n "[$(date +'%Y-%m-%d %H:%M')] "
        btrfs subvolume snapshot -r $v $v.daily-$(date +%Y-%m-%d)
        sync
    else
        if [ $DEBUG -eq 1 ]; then
            echo "[$(date +'%Y-%m-%d %H:%M')] Snapshot $v.daily-$(date +%Y-%m-%d) already exists"
        fi
    fi

    # Cleaning snapshots older than 7 days
    while [ $(ls -d $v.daily-* | wc -l) -gt 7 ]; do
        echo -n "[$(date +'%Y-%m-%d %H:%M')] "
        btrfs subvolume delete $(ls -d $v.daily-* | head -n1)
    done
done
